In [7]:
import pandas as pd

In [8]:
sous_alim = pd.read_csv(r"C:\Users\nasso\Downloads\fao-6a6b22faa98d4066102032\FAO\fr_sousalimentation.csv")

In [18]:
sous_alim

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6.6,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN
1017,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,7.8,F,Estimation FAO,NaN
1018,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,8.2,F,Estimation FAO,NaN
1019,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,8.5,F,Estimation FAO,NaN

In [9]:
print(sous_alim.shape)
print(sous_alim["Année"].unique())
print(sous_alim["Valeur"].isna().sum(), "/", len(sous_alim))

(1020, 15)
<StringArray>
['2012-2014', '2013-2015', '2014-2016', '2015-2017', '2016-2018']
Length: 5, dtype: str
415 / 1020

In [10]:
pd.crosstab(sous_alim["Année"], sous_alim["Valeur"].isna())

Valeur     False  True
Année
2012-2014    120     84
2013-2015    120     84
2014-2016    121     83
2015-2017    122     82
2016-2018    122     82

In [13]:
anim = pd.read_csv(r"C:\Users\nasso\Downloads\fao-6a6b22faa98d4066102032\FAO\fr_animaux.csv")
cer =  pd.read_csv(r"C:\Users\nasso\Downloads\fao-6a6b22faa98d4066102032\FAO\fr_céréales.csv")
popu = pd.read_csv(r"C:\Users\nasso\Downloads\fao-6a6b22faa98d4066102032\FAO\fr_population.csv")
vege = pd.read_csv(r"C:\Users\nasso\Downloads\fao-6a6b22faa98d4066102032\FAO\fr_vegetaux.csv")
print("Sous-alimentation :", sous_alim["Zone"].nunique())
print("Animaux           :", anim["Zone"].nunique())
print("Céréales          :", cer["Zone"].nunique())
print("Population        :", popu["Zone"].nunique())
print("Végétaux          :", vege["Zone"].nunique())

Sous-alimentation : 204
Animaux           : 175
Céréales          : 167
Population        : 175
Végétaux          : 175

In [22]:
print("Population :", popu["Unité"].unique())
print("Sous-alim  :", sous_alim["Unité"].unique())
print("Céréales   :", cer["Unité"].unique())
print("Animaux    :", anim["Unité"].unique())
print("Végétaux   :", vege["Unité"].unique())

Population : <StringArray>
['1000 personnes']
Length: 1, dtype: str
Sous-alim  : <StringArray>
['millions']
Length: 1, dtype: str
Céréales   : <StringArray>
['Milliers de tonnes']
Length: 1, dtype: str
Animaux    : <StringArray>
['Milliers de tonnes', 'kg', 'Kcal/personne/jour', 'g/personne/jour']
Length: 4, dtype: str
Végétaux   : <StringArray>
['Milliers de tonnes', 'kg', 'Kcal/personne/jour', 'g/personne/jour']
Length: 4, dtype: str

In [23]:
anim[["Élément", "Unité"]].drop_duplicates()

                                               Élément               Unité
0                                           Production  Milliers de tonnes
1                              Importations - Quantité  Milliers de tonnes
2                             Disponibilité intérieure  Milliers de tonnes
3                                           Nourriture  Milliers de tonnes
4    Disponibilité alimentaire en quantité (kg/pers...                  kg
5       Disponibilité alimentaire (Kcal/personne/jour)  Kcal/personne/jour
6    Disponibilité de protéines en quantité (g/pers...     g/personne/jour
7    Disponibilité de matière grasse en quantité (g...     g/personne/jour
64                                            Semences  Milliers de tonnes
65                                              Pertes  Milliers de tonnes
73                             Exportations - Quantité  Milliers de tonnes
75                               Aliments pour animaux  Milliers de tonnes
85               Autres utilisations (non alimentaire)  Milliers de tonnes
93                                  Variation de stock  Milliers de tonnes
223                                         Traitement  Milliers de tonnes